# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
