# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0002_auto_20170622_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
